services:
    spaceninjaserver:
        volumes:
            - ./docker-data/conf:/app/conf
            - ./docker-data/static-data:/app/static/data
            - ./docker-data/logs:/app/logs
        ports:
            - 80:80
            - 443:443

        # Normally, the image is fetched from Docker Hub, but you can use the local Dockerfile by swapping the following two fields.
        # Works best when using `docker-compose up --force-recreate --build`.
        image: openwf/spaceninjaserver:latest
        #build: .

        depends_on:
            - mongodb
    mongodb:
        image: docker.io/library/mongo:8.0.0-noble
        environment:
            MONGO_INITDB_ROOT_USERNAME: openwfagent
            MONGO_INITDB_ROOT_PASSWORD: spaceninjaserver
        volumes:
            - ./docker-data/database:/data/db
        command: mongod --quiet --logpath /dev/null
