name: Build
on:
    push:
        branches: ["main"]
    pull_request: {}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: ">=20.6.0"
            - run: npm ci
            - run: cp config-vanilla.json config.json
            - run: npm run verify
            - run: npm run lint:ci
            - run: npm run prettier
            - run: npm run update-translations
            - run: npm run fix-imports
            - name: Fail if there are uncommitted changes
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                    echo "Uncommitted changes detected:"
                    git status
                    git --no-pager diff
                    exit 1
                  fi
