name: Build
on:
    push: {}
    pull_request: {}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
            - run: npm ci
            - run: cp config.json.example config.json
            - run: npm run verify
            - run: npm run lint
